<?php 

/**
 * @file
 * Implements various hooks and functions to run the idfive Move Descriptions.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityFormInterface;

/**
 * Implements hook_help().
 *
 * Shows the module's readme file on the help page.
 */
function idfive_move_description_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.idfive_move_description':
        $filepath = dirname(__FILE__) . '/README.md';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
        else {
          $filepath = dirname(__FILE__) . '/README.txt';
          if (file_exists($filepath)) {
            $readme = file_get_contents($filepath);
          }
        }
        if (!isset($readme)) {
          return NULL;
        }
        if (\Drupal::moduleHandler()->moduleExists('markdown')) {
          // TODO Add markdown support.
          $output = '<pre>' . $readme . '</pre>';
        } else {
          $output = '<pre>' . $readme . '</pre>';
        }
  
        return $output;
    }
}

/**
 * Implements hook_preprocess_form_element().
 *
 * Moves all descriptions to above the field.
 */
function idfive_move_description_preprocess_form_element(&$variables) {
    // Possibly restrict by type in the future
    // dsm($variables['element']['#type']);
    $variables['description_display'] = 'before';
}

/**
 * Implements hook_form_alter().
 * 
 * Adds the simple css for the forms
 */
function idfive_move_description_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  $formObject = $form_state->getFormObject();
  if ($formObject instanceof EntityFormInterface) {
    $entity = $formObject->getEntity();
      $form['#attached']['library'][] = 'idfive_move_description/idfive_move_description.modifiers';
  }
}