_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  ajax_loader: 0
  allowed_formats: 0
  audiofield: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  conditional_fields: 0
  config: 0
  config_batch_export: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  idfive_admin_toolbar: 0
  idfive_lazyload: 0
  idfive_move_description: 0
  idfive_paragraphs: 0
  idfive_sidebar_menu: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_resmushit: 0
  imageapi_optimize_tinypng: 0
  inline_entity_form: 0
  ip_accordion: 0
  ip_blockquote: 0
  ip_button_link: 0
  ip_callout: 0
  ip_card: 0
  ip_carousel: 0
  ip_html: 0
  ip_image: 0
  ip_table: 0
  ip_video: 0
  ip_views_embed: 0
  ip_webform_embed: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  link: 0
  link_attributes: 0
  link_attributes_menu_link_content: 0
  link_target: 0
  linkit: 0
  linkit_attributes: 0
  markdown: 0
  markup: 0
  media: 0
  media_entity_download: 0
  menu_parent_form_ui: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  module_filter: 0
  msac_profiles: 0
  mysql: 0
  node: 0
  node_delete_redirect: 0
  node_title_help_text: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  rest: 0
  search: 0
  search_api: 0
  serialization: 0
  shortcut: 0
  shs: 0
  smart_trim: 0
  syslog: 0
  system: 0
  tablefield: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  text_summary_options: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  viewfield: 0
  views_data_export: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  weight: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  bartik: 0
  seven: 0
  idfive: 0
  msac: 0
  stable9: 0
profile: standard
