gmap_polygon_field_api_key: AIzaSyBa9IWSX7dzq5hGUB0rTs2516WGs7W5Qo4
gmap_polygon_field_stroke_color: '#000000'
gmap_polygon_field_stroke_opacity: '1'
gmap_polygon_field_stroke_weight: '3'
gmap_polygon_field_fill_color: '#000000'
