_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 2f5c7598-545a-432d-adb6-196d8d298e6a
name: 'Maryland State Arts Council'
mail: site_admin@msac.org
slogan: ''
page:
  403: ''
  404: /node/240
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
