_core:
  default_config_hash: Z5MXifrF77GEAgx0GQ6iWT8wStjFuY8BD9OruofWTJ8
langcode: en
message: "MSAC's website is going live soon! The site will be live by 5 PM Friday, March 05, 2021. Please visit msac.org to edit your profile once the new site is up and ready. Thank you for your patience."
