field.widget.settings.linkit_attributes:
  type: field.widget.settings.linkit
  label: 'Link with attributes settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    enabled_attributes:
      type: sequence
      sequence:
        type: boolean
        label: 'Enabled'
    open_tab_onfill:
      type: boolean
      label: 'Open the attributes tab when at least one attribute is provided.'
